alias smapi='cd ~/Coding/smapp/smapi && workon smapi && pyenv version'
alias smdecider='cd ~/Coding/smapp/smdecider && workon smdecider && pyenv version'
alias smworker='cd ~/Coding/smapp/smworker && workon smworker && pyenv version'
alias smchef='cd ~/Coding/smapp/smchef && workon smchef && pyenv version'
alias smclient='cd ~/Coding/smapp/smclient && workon smclient && pyenv version'
alias houston='sh ~/Coding/smapp/smhouston/houston && workon houston && pyenv version'
